[CmdletBinding()]
param(
    [string]$RepositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
)

$ErrorActionPreference = 'Stop'

function Assert-Throws {
    param(
        [Parameter(Mandatory = $true)][scriptblock]$Script,
        [Parameter(Mandatory = $true)][string]$Message
    )

    try {
        & $Script
    } catch {
        return
    }
    throw $Message
}

function Assert-Contains {
    param(
        [Parameter(Mandatory = $true)][string[]]$Actual,
        [Parameter(Mandatory = $true)][string]$Expected,
        [Parameter(Mandatory = $true)][string]$Message
    )

    if (-not ($Actual -contains $Expected)) {
        throw "$Message Expected '$Expected'."
    }
}

$deployPath = Join-Path $RepositoryRoot 'scripts\windows\vmware\deploy-wheel.ps1'
$deploySource = Get-Content -LiteralPath $deployPath -Raw
$executionMarker = '$resolvedRepoRoot = Resolve-RepoRoot -Path $RepoRoot'
$executionIndex = $deploySource.IndexOf($executionMarker, [System.StringComparison]::Ordinal)
if ($executionIndex -lt 0) {
    throw 'Unable to locate the deploy-wheel execution boundary.'
}
Invoke-Expression $deploySource.Substring(0, $executionIndex)

Assert-OnePasswordEnvironmentId -EnvironmentId 'blgexucrwfr2dtsxe2q4uu7dp4'
Assert-OnePasswordEnvironmentSupport -RunHelp "Flags:`n  --environment string"
Assert-Throws {
    Assert-OnePasswordEnvironmentId -EnvironmentId 'not safe'
} 'An unsafe Environment ID must fail closed.'
Assert-Throws {
    Assert-OnePasswordEnvironmentSupport -RunHelp 'Flags:`n  --env-file string'
} 'A CLI without Environment loading must fail closed.'

$script:bridgeServerProcessFixture = [pscustomobject]@{
    CommandLine = 'pwsh.exe -File C:\repo\deploy-wheel.ps1 -OnePasswordEnvironmentId blgexucrwfr2dtsxe2q4uu7dp4'
}
function Get-CimInstance {
    param([Parameter(ValueFromRemainingArguments = $true)]$Arguments)
    return $script:bridgeServerProcessFixture
}
try {
    if ((Get-OnePasswordBridgeServerEnvironmentId -ServerProcessId 1234) -ne 'blgexucrwfr2dtsxe2q4uu7dp4') {
        throw 'The bridge must recover the Environment ID from the deploy-script parent.'
    }
    $script:bridgeServerProcessFixture.CommandLine = 'pwsh.exe -File C:\repo\deploy-wheel.ps1 -OnePasswordBridgeHandle 1234'
    if (Get-OnePasswordBridgeServerEnvironmentId -ServerProcessId 1234) {
        throw 'A direct op run without the parent-selected Environment ID must fail closed.'
    }
} finally {
    Remove-Item Function:\Get-CimInstance -ErrorAction SilentlyContinue
    Remove-Variable bridgeServerProcessFixture -Scope Script -ErrorAction SilentlyContinue
}

$boundParameters = @{
    OnePasswordEnvironmentId = 'blgexucrwfr2dtsxe2q4uu7dp4'
    OnePasswordBridgeHandle = 'caller-controlled-value-must-not-forward'
    IpAddress = '192.0.2.10'
    SkipBuild = [System.Management.Automation.SwitchParameter]::new($true)
}
$childArguments = Get-OnePasswordChildArguments `
    -BoundParameters $boundParameters `
    -ScriptPath 'C:\repo\deploy-wheel.ps1'
if ($childArguments -contains '-OnePasswordEnvironmentChild') {
    throw 'The bridge child must not be authorized by a caller-selectable switch.'
}
Assert-Contains -Actual $childArguments -Expected '-IpAddress' -Message 'Bound deployment arguments must be forwarded.'
Assert-Contains -Actual $childArguments -Expected '192.0.2.10' -Message 'Bound deployment values must be forwarded.'
if ($childArguments -contains 'blgexucrwfr2dtsxe2q4uu7dp4') {
    throw 'The Environment ID must not be forwarded to the bridge child.'
}
if ($childArguments -contains 'caller-controlled-value-must-not-forward') {
    throw 'The bridge authorization values must be generated by the bridge and must not be forwarded from caller parameters.'
}

Remove-Item Env:\DEFAULT_ADMIN_PASSWORD -ErrorAction SilentlyContinue
if ((Resolve-OnePasswordChildPassword) -ne '') {
    throw 'The ordinary key/agent path must not consume DEFAULT_ADMIN_PASSWORD.'
}
$env:DEFAULT_ADMIN_PASSWORD = 'fixture-secret-is-not-output'
Assert-Throws {
    Resolve-OnePasswordChildPassword
} 'A caller-provided DEFAULT_ADMIN_PASSWORD without an authenticated op process must fail closed.'
function Assert-OnePasswordBridgeProcess {}
try {
    if ((Resolve-OnePasswordChildPassword) -ne 'fixture-secret-is-not-output') {
        throw 'The bridge child did not consume the named Environment variable.'
    }
    if (Test-Path Env:\DEFAULT_ADMIN_PASSWORD) {
        throw 'The bridge child must clear DEFAULT_ADMIN_PASSWORD immediately after capture.'
    }
} finally {
    Remove-Item Env:\DEFAULT_ADMIN_PASSWORD -ErrorAction SilentlyContinue
}
function Test-OnePasswordBridgeProcess { return $true }
Assert-Throws {
    Resolve-OnePasswordChildPassword
} 'An authenticated bridge child without DEFAULT_ADMIN_PASSWORD must fail closed.'
Remove-Item Function:\Test-OnePasswordBridgeProcess -ErrorAction SilentlyContinue

$scriptText = $deploySource
if ($scriptText.Contains('ATLASO_DEPLOY_SSH_PASSWORD', [System.StringComparison]::Ordinal)) {
    throw 'The legacy ATLASO_DEPLOY_SSH_PASSWORD fallback must remain unavailable.'
}
if (-not $scriptText.Contains('paramiko.RejectPolicy()', [System.StringComparison]::Ordinal)) {
    throw 'Password-backed deployment must reject unknown SSH host keys.'
}
if (-not $scriptText.Contains('auth_interactive', [System.StringComparison]::Ordinal) -or
    -not $scriptText.Contains('connect_password_or_keyboard_interactive', [System.StringComparison]::Ordinal)) {
    throw 'Password-backed deployment must support keyboard-interactive SSH authentication.'
}
if (-not $scriptText.Contains('auth_password(username, password, fallback=False)', [System.StringComparison]::Ordinal)) {
    throw 'Password-backed deployment must disable Paramiko interactive fallback before validating prompts.'
}
if (-not $scriptText.Contains('get_pty=False', [System.StringComparison]::Ordinal) -or
    -not $scriptText.Contains('shutdown_write()', [System.StringComparison]::Ordinal)) {
    throw 'Password-backed sudo handoff must remain noninteractive.'
}
if (-not $scriptText.Contains('ConvertTo-WindowsSshRemoteCommand', [System.StringComparison]::Ordinal) -or
    -not $scriptText.Contains('base64 -d | sh', [System.StringComparison]::Ordinal)) {
    throw 'Windows key-backed SSH must use the PowerShell login-shell transport wrapper.'
}
if (-not $scriptText.Contains('Secret redaction failed', [System.StringComparison]::Ordinal)) {
    throw 'Password-backed deployment must fail closed when output redaction fails.'
}
if (-not $scriptText.Contains('Remove-Item Env:\DEFAULT_ADMIN_PASSWORD', [System.StringComparison]::Ordinal)) {
    throw 'The bridge child must clear the source Environment variable after capture.'
}
if ($scriptText.Contains('[switch]$OnePasswordEnvironmentChild', [System.StringComparison]::Ordinal)) {
    throw 'The bridge child must not expose a caller-selectable authorization switch.'
}
if (-not $scriptText.Contains('Get-CimInstance -ClassName Win32_Process', [System.StringComparison]::Ordinal)) {
    throw 'The bridge child must authenticate its op.exe process ancestry.'
}
if (-not $scriptText.Contains('Get-OnePasswordBridgeServerEnvironmentId', [System.StringComparison]::Ordinal) -or
    -not $scriptText.Contains('$trustedEnvironmentId', [System.StringComparison]::Ordinal) -or
    -not $scriptText.Contains('$isDirectOpChild', [System.StringComparison]::Ordinal)) {
    throw 'The bridge child must bind the inherited handle to the trusted parent-selected Environment.'
}
if (-not $scriptText.Contains('Test-OnePasswordBridgeProcess', [System.StringComparison]::Ordinal)) {
    throw 'The bridge child must fail closed when the authenticated Environment omits DEFAULT_ADMIN_PASSWORD.'
}
if (-not $scriptText.Contains('deploy-wheel\.ps1', [System.StringComparison]::Ordinal) -or
    -not $scriptText.Contains('-OnePasswordEnvironmentId', [System.StringComparison]::Ordinal)) {
    throw 'The bridge child must authenticate the parent deploy-wheel invocation.'
}
if (-not $scriptText.Contains('$opEnvironment.Success', [System.StringComparison]::Ordinal)) {
    throw 'The bridge child must bind op --environment to the requested Environment ID.'
}
if (-not $scriptText.Contains('AnonymousPipeServerStream', [System.StringComparison]::Ordinal) -or
    -not $scriptText.Contains('AnonymousPipeClientStream', [System.StringComparison]::Ordinal) -or
    -not $scriptText.Contains('GetClientHandleAsString', [System.StringComparison]::Ordinal) -or
    -not $scriptText.Contains('HandleInheritability]::Inheritable', [System.StringComparison]::Ordinal) -or
    -not $scriptText.Contains('GetNamedPipeServerProcessId', [System.StringComparison]::Ordinal) -or
    -not $scriptText.Contains('Test-OnePasswordBridgeServerAncestor', [System.StringComparison]::Ordinal)) {
    throw 'The bridge must bind the child to an inherited anonymous-pipe handle owned by its process ancestry.'
}
if ($scriptText.Contains('OnePasswordBridgeNonce', [System.StringComparison]::Ordinal) -or
    $scriptText.Contains('OnePasswordBridgeEnvironmentId', [System.StringComparison]::Ordinal) -or
    $scriptText.Contains('OnePasswordBridgePipeName', [System.StringComparison]::Ordinal)) {
    throw 'Bridge authorization must not use caller-controlled Environment, nonce, or pipe-name parameters.'
}
if (-not $scriptText.Contains('read_paramiko_command_output', [System.StringComparison]::Ordinal) -or
    -not $scriptText.Contains('recv_stderr_ready', [System.StringComparison]::Ordinal) -or
    -not $scriptText.Contains('recv_ready', [System.StringComparison]::Ordinal) -or
    -not $scriptText.Contains('time.monotonic', [System.StringComparison]::Ordinal) -or
    -not $scriptText.Contains('args.timeout + 60', [System.StringComparison]::Ordinal)) {
    throw 'Password-backed deployment must drain Paramiko stdout and stderr without channel deadlock.'
}
if ($scriptText.Contains('$invokingProcess.CommandLine', [System.StringComparison]::Ordinal)) {
    throw 'Bridge authorization must not depend on the interactive PowerShell startup command line.'
}

Write-Output 'Deploy wheel 1Password bridge tests passed.'
