"""Contract tests for automatic wheel publication and manual-release handoff."""

from __future__ import annotations

import json
import zipfile
from pathlib import Path
from types import SimpleNamespace

import pytest

from scripts import wheel_artifact

VERSION = "1.2.3"
COMMIT = "a" * 40
BUILT_AT = "2026-08-29T01:02:03Z"
REPOSITORY = "mdaneri/Atlaso"


def test_timestamp_validation_preserves_timezone_aware_commit_representation() -> None:
    """Preserve Git's exact commit timestamp so legacy wheel bytes remain reproducible."""

    offset_timestamp = "2026-08-29T10:22:06-07:00"
    assert wheel_artifact._validate_timestamp(offset_timestamp) == offset_timestamp
    with pytest.raises(wheel_artifact.WheelArtifactError, match="timezone-aware"):
        wheel_artifact._validate_timestamp("2026-08-29T10:22:06")


def test_create_artifact_builds_from_explicit_source_root(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Use protected tooling while packaging only the admitted target source.

    Args:
        monkeypatch: Isolated replacement for the package build and final verifier.
        tmp_path: Isolated source and artifact directories.
    """

    source_root = tmp_path / "target-source"
    source_root.mkdir()
    (source_root / "pyproject.toml").write_text(
        f'[project]\nname = "atlaso"\nversion = "{VERSION}"\n', encoding="utf-8"
    )
    observed: dict[str, object] = {}

    def fake_build(
        target: Path, *, commit: str, built_at: str, source_root: Path
    ) -> Path:
        """Record the source root passed to the protected build helper.

        Args:
            target: Temporary wheel build directory.
            commit: Exact admitted source commit.
            built_at: Exact timezone-aware commit timestamp.
            source_root: Exact admitted source checkout.
        """

        observed.update(
            source_root=source_root,
            commit=commit,
            built_at=built_at,
        )
        wheel_root = target / "application-wheel"
        wheel_root.mkdir()
        wheel = wheel_root / f"atlaso-{VERSION}-py3-none-any.whl"
        wheel.write_bytes(b"wheel")
        return wheel

    monkeypatch.setattr(wheel_artifact, "build_application_wheel", fake_build)
    monkeypatch.setattr(wheel_artifact, "verify_artifact", lambda *args, **kwargs: None)
    output = tmp_path / "artifact"

    wheel_artifact.create_artifact(
        SimpleNamespace(
            source_root=source_root,
            output=output,
            repository=REPOSITORY,
            version=VERSION,
            commit=COMMIT,
            built_at=BUILT_AT,
            source_ci_run_id=101,
            source_ci_run_attempt=1,
            publisher_run_id=202,
            publisher_run_attempt=1,
        )
    )

    assert observed == {
        "source_root": source_root,
        "commit": COMMIT,
        "built_at": BUILT_AT,
    }
    identity = json.loads((output / wheel_artifact.IDENTITY_NAME).read_text(encoding="utf-8"))
    assert identity["version"] == VERSION
    assert identity["commit"] == COMMIT


def _write_candidate(
    root: Path,
    *,
    publisher_run_id: int,
    publisher_run_attempt: int = 1,
    wheel_payload_suffix: bytes = b"",
    embedded_commit: str = COMMIT,
) -> tuple[Path, dict[str, object]]:
    """Create one minimal extracted wheel artifact fixture.

    Args:
        root: Fixture output directory.
        publisher_run_id: Publisher run identity.
        publisher_run_attempt: Publisher attempt identity.
        wheel_payload_suffix: Optional divergent bytes for collision coverage.
        embedded_commit: Commit written into Atlaso build metadata.
    """

    root.mkdir(parents=True, exist_ok=True)
    wheel = root / f"atlaso-{VERSION}-py3-none-any.whl"
    with zipfile.ZipFile(wheel, "w") as archive:
        archive.writestr(
            f"atlaso-{VERSION}.dist-info/METADATA",
            f"Metadata-Version: 2.4\nName: atlaso\nVersion: {VERSION}\n\n".encode(),
        )
        build_metadata = (
            '"""Build metadata generated by scripts/build_release_bundle.py."""\n'
            f'BUILD_VERSION = "{VERSION}"\n'
            f'GIT_COMMIT = "{embedded_commit}"\n'
            f'BUILD_TIME_UTC = "{BUILT_AT}"\n'
        ).replace("\n", "\r\n")
        archive.writestr("atlaso/_build.py", build_metadata.encode() + wheel_payload_suffix)
    identity: dict[str, object] = {
        "schema_version": 1,
        "kind": "atlaso-python-wheel",
        "repository": REPOSITORY,
        "version": VERSION,
        "commit": COMMIT,
        "built_at": BUILT_AT,
        "source_ci": {
            "workflow": "CI",
            "workflow_file": "ci.yml",
            "run_id": 101,
            "run_attempt": 1,
        },
        "publisher": {
            "workflow": "Publish Python wheel",
            "workflow_file": "wheel.yml",
            "run_id": publisher_run_id,
            "run_attempt": publisher_run_attempt,
        },
        "artifact": {
            "name": wheel_artifact.artifact_name(VERSION, COMMIT),
            "retention_days": wheel_artifact.RETENTION_DAYS,
        },
        "wheel": {
            "filename": wheel.name,
            "sha256": wheel_artifact.sha256(wheel),
            "size": wheel.stat().st_size,
        },
    }
    (root / wheel_artifact.IDENTITY_NAME).write_bytes(wheel_artifact.canonical_json(identity))
    return wheel, identity


def test_verify_artifact_binds_repository_version_commit_digest_and_runs(tmp_path: Path) -> None:
    """Accept only an exact canonical handoff and embedded wheel build identity.

    Args:
        tmp_path: Isolated artifact directory.
    """

    wheel, identity = _write_candidate(tmp_path, publisher_run_id=202)

    verified_wheel, verified_identity = wheel_artifact.verify_artifact(
        tmp_path,
        expected_repository=REPOSITORY,
        expected_version=VERSION,
        expected_commit=COMMIT,
        expected_publisher_run_id=202,
    )

    assert verified_wheel == wheel
    assert verified_identity == identity


def test_verify_artifact_rejects_digest_and_embedded_identity_mismatch(tmp_path: Path) -> None:
    """Reject both changed bytes and a wheel built from another commit.

    Args:
        tmp_path: Isolated artifact directory.
    """

    wheel, _identity = _write_candidate(tmp_path / "digest", publisher_run_id=202)
    wheel.write_bytes(wheel.read_bytes() + b"changed")
    with pytest.raises(wheel_artifact.WheelArtifactError, match="size|digest"):
        wheel_artifact.verify_artifact(
            tmp_path / "digest",
            expected_repository=REPOSITORY,
            expected_version=VERSION,
            expected_commit=COMMIT,
        )

    _write_candidate(tmp_path / "commit", publisher_run_id=203, embedded_commit="b" * 40)
    with pytest.raises(wheel_artifact.WheelArtifactError, match="embedded build identity"):
        wheel_artifact.verify_artifact(
            tmp_path / "commit",
            expected_repository=REPOSITORY,
            expected_version=VERSION,
            expected_commit=COMMIT,
        )


def test_select_artifact_accepts_identical_retries_and_preserves_first_run(tmp_path: Path) -> None:
    """Keep the first exact handoff stable across byte-identical retries.

    Args:
        tmp_path: Isolated artifact directory.
    """

    candidates = tmp_path / "candidates"
    first, _identity = _write_candidate(
        candidates / "202-301", publisher_run_id=202, publisher_run_attempt=1
    )
    second, _identity = _write_candidate(
        candidates / "202-302", publisher_run_id=202, publisher_run_attempt=2
    )
    assert first.read_bytes() == second.read_bytes()
    output = tmp_path / "selected"

    args = type(
        "Args",
        (),
        {
            "candidates": candidates,
            "output": output,
            "repository": REPOSITORY,
            "version": VERSION,
            "commit": COMMIT,
        },
    )()
    wheel_artifact.select_artifact(args)

    selected = json.loads((output / wheel_artifact.IDENTITY_NAME).read_text(encoding="utf-8"))
    assert selected["publisher"]["run_id"] == 202
    assert selected["publisher"]["run_attempt"] == 1


def test_select_artifact_fails_closed_on_divergent_collision(tmp_path: Path) -> None:
    """Reject retained artifacts that claim one identity but contain different wheel bytes.

    Args:
        tmp_path: Isolated artifact directory.
    """

    candidates = tmp_path / "candidates"
    _write_candidate(candidates / "202-301", publisher_run_id=202)
    _write_candidate(
        candidates / "202-302",
        publisher_run_id=202,
        publisher_run_attempt=2,
        wheel_payload_suffix=b"# retry",
    )
    args = type(
        "Args",
        (),
        {
            "candidates": candidates,
            "output": tmp_path / "selected",
            "repository": REPOSITORY,
            "version": VERSION,
            "commit": COMMIT,
        },
    )()

    with pytest.raises(wheel_artifact.WheelArtifactError, match="collide"):
        wheel_artifact.select_artifact(args)


def test_extract_artifact_rejects_unexpected_archive_members(tmp_path: Path) -> None:
    """Extract only the two flat files allowed by the automatic artifact contract.

    Args:
        tmp_path: Isolated artifact directory.
    """

    archive = tmp_path / "artifact.zip"
    with zipfile.ZipFile(archive, "w") as payload:
        payload.writestr(wheel_artifact.IDENTITY_NAME, "{}\n")
        payload.writestr(f"atlaso-{VERSION}-py3-none-any.whl", b"wheel")
        payload.writestr("unexpected.txt", b"no")
    args = type(
        "Args",
        (),
        {"archive": archive, "output": tmp_path / "output"},
    )()

    with pytest.raises(wheel_artifact.WheelArtifactError, match="unexpected payload"):
        wheel_artifact.extract_artifact(args)
