from pathlib import Path

from scripts.check_dependency_policy import LOCK_POLICIES, validate
from scripts.compile_requirements import LOCK_TARGETS, _compile_command


def write_valid_policy(root: Path) -> None:
    dependabot = root / ".github" / "dependabot.yml"
    dependabot.parent.mkdir(parents=True)
    dependabot.write_text(
        """
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    cooldown:
      default-days: 7
      include:
        - "*"
  - package-ecosystem: github-actions
    directory: /
""".lstrip(),
        encoding="utf-8",
    )
    for policy in LOCK_POLICIES:
        options = ["--generate-hashes", f"--output-file={policy.path}"]
        if policy.allow_unsafe:
            options.append("--allow-unsafe")
        options.append("--uploaded-prior-to=P7D")
        command = " ".join(("pip-compile", *options, *policy.inputs))
        path = root / policy.path
        path.write_text(
            "\n".join(
                (
                    "#",
                    "# This file is autogenerated by pip-compile with Python 3.14",
                    "# by the following command:",
                    "#",
                    f"#    {command}",
                    "#",
                    "example==1.0.0 \\",
                    "    --hash=sha256:" + ("a" * 64),
                    "",
                )
            ),
            encoding="utf-8",
        )


def test_dependency_policy_accepts_all_generated_locks(tmp_path: Path) -> None:
    write_valid_policy(tmp_path)

    assert validate(tmp_path) == []


def test_dependency_policy_rejects_missing_dependabot_cooldown(
    tmp_path: Path,
) -> None:
    write_valid_policy(tmp_path)
    dependabot = tmp_path / ".github" / "dependabot.yml"
    dependabot.write_text(
        dependabot.read_text(encoding="utf-8").replace("      default-days: 7\n", ""),
        encoding="utf-8",
    )

    assert any("7-day cooldown" in error for error in validate(tmp_path))


def test_dependency_policy_rejects_lock_without_upload_cutoff(tmp_path: Path) -> None:
    write_valid_policy(tmp_path)
    path = tmp_path / "requirements-appliance.lock"
    path.write_text(
        path.read_text(encoding="utf-8").replace(" --uploaded-prior-to=P7D", ""),
        encoding="utf-8",
    )

    assert any(
        "requirements-appliance.lock: generation command is missing "
        "--uploaded-prior-to=P7D" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_rejects_unhashed_pin(tmp_path: Path) -> None:
    write_valid_policy(tmp_path)
    path = tmp_path / "requirements-docs.lock"
    path.write_text(
        path.read_text(encoding="utf-8").replace(
            "    --hash=sha256:" + ("a" * 64), ""
        ),
        encoding="utf-8",
    )

    assert any(
        "requirements-docs.lock:7: pinned requirement has no SHA256 hash" in error
        for error in validate(tmp_path)
    )


def test_lock_compiler_applies_upload_cutoff_to_every_target() -> None:
    for target in LOCK_TARGETS:
        command = _compile_command(target, upgrade=False)

        assert "--uploaded-prior-to=P7D" in command
        assert "--generate-hashes" in command
        assert f"--output-file={target.output}" in command
        assert ("--allow-unsafe" in command) is target.allow_unsafe


def test_lock_compiler_adds_upgrade_only_when_requested() -> None:
    target = LOCK_TARGETS[0]

    assert "--upgrade" not in _compile_command(target, upgrade=False)
    assert "--upgrade" in _compile_command(target, upgrade=True)
