"""Test dependency policy behavior."""

import io
import json
from pathlib import Path

from scripts.check_dependency_policy import LOCK_POLICIES, validate
from scripts.compile_requirements import (
    LOCK_TARGETS,
    _assert_index_provides_upload_times,
    _compile_command,
    _compile_environment,
    _validated_index_url,
)


def write_valid_policy(root: Path) -> None:
    """Persist valid policy.

    Args:
        root: Repository or filesystem root searched by the operation.
    """
    dependabot = root / ".github" / "dependabot.yml"
    dependabot.parent.mkdir(parents=True)
    dependabot.write_text(
        """
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    cooldown:
      default-days: 7
      include:
        - "*"
  - package-ecosystem: github-actions
    directory: /
""".lstrip(),
        encoding="utf-8",
    )
    for policy in LOCK_POLICIES:
        options = [
            "--generate-hashes",
            "--index-url=https://pypi.org/simple",
            "--no-emit-index-url",
            f"--output-file={policy.path}",
        ]
        if policy.allow_unsafe:
            options.append("--allow-unsafe")
        options.append("--uploaded-prior-to=P7D")
        command = " ".join(("pip-compile", *options, *policy.inputs))
        path = root / policy.path
        path.write_text(
            "\n".join(
                (
                    "#",
                    "# This file is autogenerated by pip-compile with Python 3.14",
                    "# by the following command:",
                    "#",
                    f"#    {command}",
                    "#",
                    "example==1.0.0 \\",
                    "    --hash=sha256:" + ("a" * 64),
                    "",
                )
            ),
            encoding="utf-8",
        )


def test_dependency_policy_accepts_all_generated_locks(tmp_path: Path) -> None:
    """Verify that dependency policy accepts all generated locks.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)

    assert validate(tmp_path) == []


def test_dependency_policy_rejects_missing_workflow_requirement_lock(
    tmp_path: Path,
) -> None:
    """Verify that workflows cannot reference a missing requirement lock.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        "run: python -m pip install --require-hashes "
        "--requirement requirements-deployment.lock\n",
        encoding="utf-8",
    )

    normalized_errors = [error.replace("\\", "/") for error in validate(tmp_path)]
    assert (
        ".github/workflows/release.yml:1: workflow requirement path is missing: "
        "requirements-deployment.lock"
    ) in normalized_errors


def test_dependency_policy_rejects_workflow_lock_outside_inventory(
    tmp_path: Path,
) -> None:
    """Verify that an existing ad hoc workflow lock is not sufficient.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    (tmp_path / "requirements-ad-hoc.lock").write_text("placeholder\n", encoding="utf-8")
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        "run: python -m pip install -r requirements-ad-hoc.lock\n",
        encoding="utf-8",
    )

    assert any(
        "workflow requirement lock is outside the generated dependency policy inventory: "
        "requirements-ad-hoc.lock" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_checks_multiline_pip_wheel_requirements(
    tmp_path: Path,
) -> None:
    """Verify non-install pip commands and continuation lines use policy locks.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    (tmp_path / "requirements-ad-hoc.lock").write_text("placeholder\n", encoding="utf-8")
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        """steps:
  - run: |
      python -m pip wheel \\
        --no-deps \\
        --requirement requirements-ad-hoc.lock
""",
        encoding="utf-8",
    )

    assert any(
        "workflow requirement lock is outside the generated dependency policy inventory: "
        "requirements-ad-hoc.lock" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_recognizes_prefixed_python_pip_invocations(
    tmp_path: Path,
) -> None:
    """Verify valid Python launch prefixes cannot bypass workflow lock policy.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    (tmp_path / "requirements-ad-hoc.lock").write_text("placeholder\n", encoding="utf-8")
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    invocations = (
        "python3.14 -m pip install -r requirements-ad-hoc.lock",
        "python -m pip.__main__ install -r requirements-ad-hoc.lock",
        "python -I -m pip.__main__ install -r requirements-ad-hoc.lock",
        "python -mpip install -r requirements-ad-hoc.lock",
        "python -mpip.__main__ install -r requirements-ad-hoc.lock",
        "python -m 'pip' install -r requirements-ad-hoc.lock",
        'python -m "pip.__main__" install -r requirements-ad-hoc.lock',
        "'python' -m 'pip' install -r requirements-ad-hoc.lock",
        '"python3.14" -m "pip.__main__" install -r requirements-ad-hoc.lock',
        "'pip' install -r requirements-ad-hoc.lock",
        "pip.exe install -r requirements-ad-hoc.lock",
        "'pip.exe' install -r requirements-ad-hoc.lock",
        "./venv/bin/pip install -r requirements-ad-hoc.lock",
        "./venv/bin/python -m pip install -r requirements-ad-hoc.lock",
        "C:\\venv\\Scripts\\pip.exe install -r requirements-ad-hoc.lock",
        "PIP_CONFIG_FILE=/dev/null python -m pip install -r requirements-ad-hoc.lock",
        "& python -m pip install -r requirements-ad-hoc.lock",
    )
    for invocation in invocations:
        workflow.write_text(f"run: {invocation}\n", encoding="utf-8")

        assert any(
            "workflow requirement lock is outside the generated dependency policy "
            "inventory: requirements-ad-hoc.lock" in error
            for error in validate(tmp_path)
        )


def test_dependency_policy_recognizes_attached_short_requirement_argument(
    tmp_path: Path,
) -> None:
    """Verify pip's attached short requirement option cannot bypass policy.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    (tmp_path / "requirements-ad-hoc.lock").write_text("placeholder\n", encoding="utf-8")
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        "run: python -m pip install -rrequirements-ad-hoc.lock\n",
        encoding="utf-8",
    )

    assert any(
        "workflow requirement lock is outside the generated dependency policy inventory: "
        "requirements-ad-hoc.lock" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_preserves_equals_in_attached_short_requirement_argument(
    tmp_path: Path,
) -> None:
    """Verify an equals-prefixed attached short option keeps pip's filename.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    (tmp_path / "=requirements-release-tools.lock").write_text(
        "placeholder\n", encoding="utf-8"
    )
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        "run: python -m pip install -r=requirements-release-tools.lock\n",
        encoding="utf-8",
    )

    assert any(
        "workflow requirement lock is outside the generated dependency policy inventory: "
        "=requirements-release-tools.lock" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_rejects_external_checkout_requirement_lock(
    tmp_path: Path,
) -> None:
    """Verify checkout prefixes cannot map external locks onto Atlaso inventory.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        """steps:
  - uses: actions/checkout@v7
    with:
      repository: attacker/other
      path: external
  - run: python -m pip install -r external/requirements-release-tools.lock
""",
        encoding="utf-8",
    )

    assert any(
        "checkout-prefixed workflow requirement is not sourced from Atlaso: "
        "external/requirements-release-tools.lock" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_limits_checkout_inputs_to_with_mapping(
    tmp_path: Path,
) -> None:
    """Verify nested step mappings cannot overwrite checkout inputs.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        """jobs:
  external:
    steps:
      - uses: actions/checkout@v7
        with:
          repository: attacker/other
        env:
          repository: mdaneri/Atlaso
      - run: python -m pip install -r requirements-release-tools.lock
""",
        encoding="utf-8",
    )

    assert any(
        "root workflow requirement is not sourced from Atlaso: "
        "requirements-release-tools.lock" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_tokenizes_escaped_requirement_flag(
    tmp_path: Path,
) -> None:
    """Verify shell escapes are removed before requirement flag matching.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    (tmp_path / "requirements-ad-hoc.lock").write_text(
        "placeholder\n", encoding="utf-8"
    )
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        "run: python -m pip install \\-r requirements-ad-hoc.lock\n",
        encoding="utf-8",
    )

    assert any(
        "workflow requirement lock is outside the generated dependency policy "
        "inventory: requirements-ad-hoc.lock" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_rejects_conditional_checkout_replacement(
    tmp_path: Path,
) -> None:
    """Verify a skipped checkout cannot replace the active external root.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        """jobs:
  conditional:
    steps:
      - uses: actions/checkout@v7
        with:
          repository: attacker/other
      - uses: actions/checkout@v7
        if: ${{ false }}
      - run: python -m pip install -r requirements-release-tools.lock
""",
        encoding="utf-8",
    )

    assert any(
        "root workflow requirement uses conditional checkout metadata: "
        "requirements-release-tools.lock" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_accepts_matching_checkout_condition(
    tmp_path: Path,
) -> None:
    """Verify identical checkout and pip conditions share source metadata.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        """jobs:
  conditional:
    steps:
      - uses: actions/checkout@v7
        if: steps.identity.outputs.ready == 'true'
      - run: python -m pip install -r requirements-release-tools.lock
        if: steps.identity.outputs.ready == 'true'
""",
        encoding="utf-8",
    )

    assert validate(tmp_path) == []


def test_dependency_policy_rejects_fallible_checkout_replacement(
    tmp_path: Path,
) -> None:
    """Verify a continued checkout cannot become trusted source metadata.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        """jobs:
  fallible:
    steps:
      - uses: actions/checkout@v7
        with:
          repository: attacker/other
      - uses: actions/checkout@v7
        continue-on-error: true
      - run: python -m pip install -r requirements-release-tools.lock
""",
        encoding="utf-8",
    )

    assert any(
        "root workflow requirement uses fallible checkout metadata: "
        "requirements-release-tools.lock" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_decodes_quoted_run_scalars(tmp_path: Path) -> None:
    """Verify quoted run scalars are decoded before command tokenization.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    (tmp_path / "requirements-ad-hoc.lock").write_text(
        "placeholder\n", encoding="utf-8"
    )
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    invocations = (
        "run: 'python -m pip install -r requirements-ad-hoc.lock'\n",
        'run: "python -m pip install -r requirements-ad-hoc.lock"\n',
    )
    for invocation in invocations:
        workflow.write_text(invocation, encoding="utf-8")

        assert any(
            "workflow requirement lock is outside the generated dependency policy "
            "inventory: requirements-ad-hoc.lock" in error
            for error in validate(tmp_path)
        )


def test_dependency_policy_rejects_untrusted_atlaso_checkout_ref(
    tmp_path: Path,
) -> None:
    """Verify arbitrary same-repository refs cannot provide policy locks.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        """steps:
  - uses: actions/checkout@v7
    with:
      ref: feature/untrusted-lock
      path: candidate
  - run: python -m pip install -r candidate/requirements-release-tools.lock
""",
        encoding="utf-8",
    )

    assert any(
        "checkout-prefixed workflow requirement uses an untrusted Atlaso ref: "
        "candidate/requirements-release-tools.lock" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_accepts_lock_from_checkout_destination(
    tmp_path: Path,
) -> None:
    """Verify checkout-prefixed target-source locks resolve to tracked inputs.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "wheel.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        """steps:
  - uses: actions/checkout@v7
    with:
      ref: ${{ steps.target.outputs.commit }}
      path: target-source
  - run: python -m pip install --require-hashes -r target-source/requirements-release-tools.lock
""",
        encoding="utf-8",
    )

    assert validate(tmp_path) == []


def test_dependency_policy_rejects_external_root_checkout_lock(
    tmp_path: Path,
) -> None:
    """Verify an external root checkout cannot supply an Atlaso-named lock.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        """jobs:
  external:
    steps:
      - uses: actions/checkout@v7
        with:
          repository: attacker/other
      - run: python -m pip install -r requirements-release-tools.lock
""",
        encoding="utf-8",
    )

    assert any(
        "root workflow requirement is not sourced from Atlaso: "
        "requirements-release-tools.lock" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_recognizes_quoted_checkout_action(
    tmp_path: Path,
) -> None:
    """Verify quoted checkout action scalars still identify external roots.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        """jobs:
  external:
    steps:
      - uses: 'actions/checkout@v7'
        with:
          repository: attacker/other
      - run: python -m pip install -r requirements-release-tools.lock
""",
        encoding="utf-8",
    )

    assert any(
        "root workflow requirement is not sourced from Atlaso: "
        "requirements-release-tools.lock" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_recognizes_checkout_action_comment(
    tmp_path: Path,
) -> None:
    """Verify an inline YAML comment does not hide an external checkout.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        """jobs:
  external:
    steps:
      - uses: actions/checkout@v7 # source
        with:
          repository: attacker/other
      - run: python -m pip install -r requirements-release-tools.lock
""",
        encoding="utf-8",
    )

    assert any(
        "root workflow requirement is not sourced from Atlaso: "
        "requirements-release-tools.lock" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_respects_quoted_shell_separators(
    tmp_path: Path,
) -> None:
    """Verify command separators inside quotes do not truncate pip arguments.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    (tmp_path / "requirements-ad-hoc.lock").write_text(
        "placeholder\n", encoding="utf-8"
    )
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        'run: python -m pip install -C "flag=a;b" -r requirements-ad-hoc.lock\n',
        encoding="utf-8",
    )

    assert any(
        "workflow requirement lock is outside the generated dependency policy "
        "inventory: requirements-ad-hoc.lock" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_respects_powershell_escaped_separators(
    tmp_path: Path,
) -> None:
    """Verify PowerShell-escaped separators do not truncate pip arguments.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    (tmp_path / "requirements-ad-hoc.lock").write_text(
        "placeholder\n", encoding="utf-8"
    )
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        "run: python -m pip install -C flag=a`;b -r requirements-ad-hoc.lock\n",
        encoding="utf-8",
    )

    assert any(
        "workflow requirement lock is outside the generated dependency policy "
        "inventory: requirements-ad-hoc.lock" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_tracks_shell_directory_changes(tmp_path: Path) -> None:
    """Verify shell directory changes affect later requirement resolution.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    invocations = (
        "cd external; python -m pip install -r requirements-release-tools.lock",
        "pushd external > /dev/null; python -m pip install -r requirements-release-tools.lock",
        "Set-Location external; python -m pip install -r requirements-release-tools.lock",
    )
    for invocation in invocations:
        workflow.write_text(
            f"""jobs:
  external:
    steps:
      - uses: actions/checkout@v7
        with:
          repository: attacker/other
          path: external
      - run: {invocation}
""",
            encoding="utf-8",
        )

        assert any(
            "checkout-prefixed workflow requirement is not sourced from Atlaso: "
            "requirements-release-tools.lock" in error
            for error in validate(tmp_path)
        )


def test_dependency_policy_tracks_multiline_shell_directory_change(
    tmp_path: Path,
) -> None:
    """Verify directory state persists across lines of one run block.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        """jobs:
  external:
    steps:
      - uses: actions/checkout@v7
        with:
          repository: attacker/other
          path: external
      - run: |
          cd external
          python -m pip install -r requirements-release-tools.lock
""",
        encoding="utf-8",
    )

    assert any(
        "checkout-prefixed workflow requirement is not sourced from Atlaso: "
        "requirements-release-tools.lock" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_preserves_folded_scalar_command_boundaries(
    tmp_path: Path,
) -> None:
    """Verify blank lines in folded run scalars retain shell state boundaries.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    folded_bodies = (
        """          cd external

          python -m pip install -r requirements-release-tools.lock
""",
        """          cd external
            python -m pip install -r requirements-release-tools.lock
""",
    )
    for folded_body in folded_bodies:
        workflow.write_text(
            f"""jobs:
  external:
    steps:
      - uses: actions/checkout@v7
        with:
          repository: attacker/other
          path: external
      - run: >
{folded_body}""",
            encoding="utf-8",
        )

        assert any(
            "checkout-prefixed workflow requirement is not sourced from Atlaso: "
            "requirements-release-tools.lock" in error
            for error in validate(tmp_path)
        )


def test_dependency_policy_rejects_nondeterministic_directory_state(
    tmp_path: Path,
) -> None:
    """Verify controlled directory actions fail closed for later requirements.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    (tmp_path / "requirements-ad-hoc.lock").write_text(
        "placeholder\n", encoding="utf-8"
    )
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    invocations = (
        "pushd external || popd; python -m pip install -r requirements-release-tools.lock",
        "cd . & python -m pip install -r requirements-ad-hoc.lock",
        "cd . | python -m pip install -r requirements-ad-hoc.lock",
    )
    for invocation in invocations:
        workflow.write_text(
            f"""jobs:
  external:
    steps:
      - uses: actions/checkout@v7
        with:
          repository: attacker/other
          path: external
      - run: {invocation}
""",
            encoding="utf-8",
        )

        assert any(
            "workflow working directory must be a literal repository path: "
            "${{ unsupported-shell-directory-control }}" in error
            for error in validate(tmp_path)
        )


def test_dependency_policy_rejects_nonliteral_checkout_path(
    tmp_path: Path,
) -> None:
    """Verify a dynamic checkout destination cannot replace root metadata.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        """jobs:
  dynamic:
    steps:
      - uses: actions/checkout@v7
        with:
          repository: attacker/other
      - uses: actions/checkout@v7
        with:
          path: ${{ env.TRUSTED_PATH }}
      - run: python -m pip install -r requirements-release-tools.lock
""",
        encoding="utf-8",
    )

    assert any(
        "workflow requirement uses nonliteral checkout path metadata: "
        "requirements-release-tools.lock" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_parses_flow_style_run_step(tmp_path: Path) -> None:
    """Verify a compact flow-style run step cannot bypass lock policy.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    (tmp_path / "requirements-ad-hoc.lock").write_text(
        "placeholder\n", encoding="utf-8"
    )
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        """jobs:
  flow:
    steps:
      - {run: "python -m pip install -r requirements-ad-hoc.lock"}
""",
        encoding="utf-8",
    )

    assert any(
        "workflow requirement lock is outside the generated dependency policy "
        "inventory: requirements-ad-hoc.lock" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_rejects_alias_valued_run_step(tmp_path: Path) -> None:
    """Verify alias-valued run fields cannot bypass lock policy.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    (tmp_path / "requirements-ad-hoc.lock").write_text("placeholder\n", encoding="utf-8")
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        """jobs:
  alias:
    steps:
      - run: &install "python -m pip install -r requirements-ad-hoc.lock"
      - run: *install
""",
        encoding="utf-8",
    )

    assert any(
        "run command uses YAML alias and cannot be policy validated: *install" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_rejects_alias_valued_flow_style_run_step(tmp_path: Path) -> None:
    """Verify flow-style alias-valued run fields cannot bypass lock policy.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    (tmp_path / "requirements-ad-hoc.lock").write_text("placeholder\n", encoding="utf-8")
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        """jobs:
  flow:
    steps:
      - {run: &install "python -m pip install -r requirements-ad-hoc.lock"}
      - {run: *install}
""",
        encoding="utf-8",
    )

    assert any(
        "run command uses YAML alias and cannot be policy validated: *install" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_parses_flow_style_checkout_inputs(
    tmp_path: Path,
) -> None:
    """Verify compact checkout inputs retain their external source metadata.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    checkout_steps = (
        """      - uses: actions/checkout@v7
        with: {repository: attacker/other}
""",
        """      - {uses: actions/checkout@v7, with: {repository: attacker/other}}
""",
    )
    for checkout_step in checkout_steps:
        workflow.write_text(
            f"""jobs:
  flow:
    steps:
{checkout_step}      - run: python -m pip install -r requirements-release-tools.lock
""",
            encoding="utf-8",
        )

        assert any(
            "root workflow requirement is not sourced from Atlaso: "
            "requirements-release-tools.lock" in error
            for error in validate(tmp_path)
        )


def test_dependency_policy_rejects_grouped_shell_requirement_resolution(
    tmp_path: Path,
) -> None:
    """Verify grouped shell directory state fails closed for requirements.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    for opening, closing in (("(", ")"), ("{", "}")):
        workflow.write_text(
            f"""jobs:
  external:
    steps:
      - uses: actions/checkout@v7
        with:
          repository: attacker/other
          path: external
      - run: |
          {opening} cd external
            python -m pip install -r requirements-release-tools.lock
          {closing}
""",
            encoding="utf-8",
        )

        assert any(
            "workflow working directory must be a literal repository path: "
            "${{ unsupported-shell-grouping }}" in error
            for error in validate(tmp_path)
        )


def test_dependency_policy_restores_shell_directory_stack(tmp_path: Path) -> None:
    """Verify pop operations restore the source used for later requirements.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    invocations = (
        "pushd tooling; popd; python -m pip install -r requirements-release-tools.lock",
        "Push-Location tooling; Pop-Location; python -m pip install -r requirements-release-tools.lock",
    )
    for invocation in invocations:
        workflow.write_text(
            f"""jobs:
  external:
    steps:
      - uses: actions/checkout@v7
        with:
          repository: attacker/other
      - uses: actions/checkout@v7
        with:
          path: tooling
      - run: {invocation}
""",
            encoding="utf-8",
        )

        assert any(
            "root workflow requirement is not sourced from Atlaso: "
            "requirements-release-tools.lock" in error
            for error in validate(tmp_path)
        )


def test_dependency_policy_treats_dot_checkout_path_as_root(
    tmp_path: Path,
) -> None:
    """Verify an explicit dot checkout path replaces the workspace root.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        """jobs:
  external:
    steps:
      - uses: actions/checkout@v7
        with:
          repository: attacker/other
          path: .
      - run: python -m pip install -r requirements-release-tools.lock
""",
        encoding="utf-8",
    )

    assert any(
        "root workflow requirement is not sourced from Atlaso: "
        "requirements-release-tools.lock" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_rejects_untrusted_atlaso_root_checkout_ref(
    tmp_path: Path,
) -> None:
    """Verify an arbitrary Atlaso root ref cannot supply policy locks.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        """jobs:
  candidate:
    steps:
      - uses: actions/checkout@v7
        with:
          ref: feature/untrusted-lock
      - run: python -m pip install -r requirements-release-tools.lock
""",
        encoding="utf-8",
    )

    assert any(
        "root workflow requirement uses an untrusted Atlaso ref: "
        "requirements-release-tools.lock" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_scopes_root_checkouts_to_their_jobs(
    tmp_path: Path,
) -> None:
    """Verify one job's external checkout does not taint another job.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        """jobs:
  external:
    steps:
      - uses: actions/checkout@v7
        with:
          repository: attacker/other
  atlaso:
    steps:
      - uses: actions/checkout@v7
      - run: python -m pip install -r requirements-release-tools.lock
""",
        encoding="utf-8",
    )

    assert validate(tmp_path) == []


def test_dependency_policy_honors_step_working_directory(
    tmp_path: Path,
) -> None:
    """Verify a step working directory selects the checkout supplying its lock.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        """jobs:
  external:
    steps:
      - uses: actions/checkout@v7
        with:
          repository: attacker/other
          path: external
      - run: python -m pip install -r requirements-release-tools.lock
        working-directory: external
""",
        encoding="utf-8",
    )

    assert any(
        "checkout-prefixed workflow requirement is not sourced from Atlaso: "
        "requirements-release-tools.lock" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_honors_job_default_working_directory(
    tmp_path: Path,
) -> None:
    """Verify a job's default working directory applies to run steps.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        """jobs:
  external:
    defaults:
      run:
        working-directory: external
    steps:
      - uses: actions/checkout@v7
        with:
          repository: attacker/other
          path: external
      - run: python -m pip install -r requirements-release-tools.lock
""",
        encoding="utf-8",
    )

    assert any(
        "checkout-prefixed workflow requirement is not sourced from Atlaso: "
        "requirements-release-tools.lock" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_honors_workflow_default_working_directory(
    tmp_path: Path,
) -> None:
    """Verify the workflow default working directory applies after job defaults.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        """defaults:
  run:
    working-directory: external
jobs:
  external:
    steps:
      - uses: actions/checkout@v7
        with:
          repository: attacker/other
          path: external
      - run: python -m pip install -r requirements-release-tools.lock
""",
        encoding="utf-8",
    )

    assert any(
        "checkout-prefixed workflow requirement is not sourced from Atlaso: "
        "requirements-release-tools.lock" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_uses_checkout_destination_history(
    tmp_path: Path,
) -> None:
    """Verify each command uses the latest preceding destination checkout.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        """jobs:
  reused:
    steps:
      - uses: actions/checkout@v7
        with:
          repository: attacker/other
          path: tooling
      - run: python -m pip install -r tooling/requirements-release-tools.lock
      - uses: actions/checkout@v7
        with:
          path: tooling
""",
        encoding="utf-8",
    )

    assert any(
        "checkout-prefixed workflow requirement is not sourced from Atlaso: "
        "tooling/requirements-release-tools.lock" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_rejects_dynamic_working_directory(
    tmp_path: Path,
) -> None:
    """Verify unresolved working-directory expressions fail closed.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    workflow = tmp_path / ".github" / "workflows" / "release.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    workflow.write_text(
        """steps:
  - run: python -m pip install -r requirements-release-tools.lock
    working-directory: ${{ matrix.source }}
""",
        encoding="utf-8",
    )

    assert any(
        "workflow working directory must be a literal repository path: "
        "${{ matrix.source }}" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_rejects_missing_dependabot_cooldown(
    tmp_path: Path,
) -> None:
    """Verify that dependency policy rejects missing dependabot cooldown.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    dependabot = tmp_path / ".github" / "dependabot.yml"
    dependabot.write_text(
        dependabot.read_text(encoding="utf-8").replace("      default-days: 7\n", ""),
        encoding="utf-8",
    )

    assert any("7-day cooldown" in error for error in validate(tmp_path))


def test_dependency_policy_rejects_lock_without_upload_cutoff(tmp_path: Path) -> None:
    """Verify that dependency policy rejects lock without upload cutoff.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    path = tmp_path / "requirements-appliance.lock"
    path.write_text(
        path.read_text(encoding="utf-8").replace(" --uploaded-prior-to=P7D", ""),
        encoding="utf-8",
    )

    assert any(
        "requirements-appliance.lock: generation command is missing "
        "--uploaded-prior-to=P7D" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_rejects_unhashed_pin(tmp_path: Path) -> None:
    """Verify that dependency policy rejects unhashed pin.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    path = tmp_path / "requirements-docs.lock"
    path.write_text(
        path.read_text(encoding="utf-8").replace(
            "    --hash=sha256:" + ("a" * 64), ""
        ),
        encoding="utf-8",
    )

    assert any(
        "requirements-docs.lock:7: pinned requirement has no SHA256 hash" in error
        for error in validate(tmp_path)
    )


def test_dependency_policy_rejects_non_exact_requirement(tmp_path: Path) -> None:
    """Verify that dependency policy rejects non exact requirement.

    Args:
        tmp_path: Temporary directory provided by pytest for isolated filesystem state.
    """
    write_valid_policy(tmp_path)
    path = tmp_path / "requirements-release-tools.lock"
    path.write_text(
        path.read_text(encoding="utf-8")
        + "second>=2.0 \\\n"
        + "    --hash=sha256:"
        + ("b" * 64)
        + "\n",
        encoding="utf-8",
    )

    assert any(
        "requirements-release-tools.lock:" in error
        and "requirement must use an exact == pin" in error
        for error in validate(tmp_path)
    )


def test_lock_compiler_applies_upload_cutoff_to_every_target() -> None:
    """Verify that lock compiler applies upload cutoff to every target."""
    for target in LOCK_TARGETS:
        command = _compile_command(target, upgrade=False)

        assert "--uploaded-prior-to=P7D" in command
        assert "--generate-hashes" in command
        assert "--index-url=https://pypi.org/simple" in command
        assert "--no-config" in command
        assert "--no-emit-index-url" in command
        assert f"--output-file={target.output}" in command
        assert ("--allow-unsafe" in command) is target.allow_unsafe


def test_lock_policy_and_generation_inventories_match() -> None:
    """Verify every policy lock is generated and every generated lock is governed."""
    assert {policy.path for policy in LOCK_POLICIES} == {
        target.output for target in LOCK_TARGETS
    }


def test_lock_compiler_adds_upgrade_only_when_requested() -> None:
    """Verify that lock compiler adds upgrade only when requested."""
    target = LOCK_TARGETS[0]

    assert "--upgrade" not in _compile_command(target, upgrade=False)
    assert "--upgrade" in _compile_command(target, upgrade=True)


def test_index_validation_requires_https_without_embedded_credentials() -> None:
    """Verify that index validation requires https without embedded credentials.

    Raises:
        AssertionError: If an expected invariant is not satisfied.
    """
    assert _validated_index_url("https://example.invalid/simple/") == (
        "https://example.invalid/simple"
    )

    for index_url in (
        "http://example.invalid/simple",
        "https://user:secret@example.invalid/simple",
    ):
        try:
            _validated_index_url(index_url)
        except RuntimeError:
            pass
        else:
            raise AssertionError(f"{index_url} should have been rejected")


def test_index_metadata_check_rejects_missing_upload_times(monkeypatch) -> None:
    """Verify that index metadata check rejects missing upload times.

    Args:
        monkeypatch: Pytest fixture used to replace dependencies for the test.


    Raises:
        AssertionError: If an expected invariant is not satisfied.
    """
    payload = {"files": [{"filename": "pip.whl"}]}
    monkeypatch.setattr(
        "urllib.request.urlopen",
        lambda request, timeout: io.BytesIO(json.dumps(payload).encode("utf-8")),
    )

    try:
        _assert_index_provides_upload_times("https://example.invalid/simple")
    except RuntimeError as exc:
        assert "does not provide complete upload-time metadata" in str(exc)
    else:
        raise AssertionError("index without upload times should have been rejected")


def test_index_metadata_check_accepts_complete_upload_times(monkeypatch) -> None:
    """Verify that index metadata check accepts complete upload times.

    Args:
        monkeypatch: Pytest fixture used to replace dependencies for the test.
    """
    payload = {
        "files": [
            {
                "filename": "pip.whl",
                "upload-time": "2026-01-01T00:00:00Z",
            }
        ]
    }
    monkeypatch.setattr(
        "urllib.request.urlopen",
        lambda request, timeout: io.BytesIO(json.dumps(payload).encode("utf-8")),
    )

    _assert_index_provides_upload_times("https://example.invalid/simple")


def test_compile_environment_ignores_unverified_package_sources(
    monkeypatch,
) -> None:
    """Verify that compile environment ignores unverified package sources.

    Args:
        monkeypatch: Pytest fixture used to replace dependencies for the test.
    """
    monkeypatch.setenv("PIP_INDEX_URL", "https://mirror.invalid/simple")
    monkeypatch.setenv("PIP_EXTRA_INDEX_URL", "https://extra.invalid/simple")
    monkeypatch.setenv("PIP_FIND_LINKS", "https://files.invalid/")

    environment = _compile_environment()

    assert environment["PIP_CONFIG_FILE"]
    assert "PIP_INDEX_URL" not in environment
    assert "PIP_EXTRA_INDEX_URL" not in environment
    assert "PIP_FIND_LINKS" not in environment
